import { Resource } from "@/types/resources";
import React from "react";
import ResourcesList from "@/components/ResourcesList";
import ClientDetailsPromptBubble from "@/components/ClientDetailsPromptBubble";

export function PrintableReferralsReport({
  resources,
  clientDescription,
}: {
  resources: Resource[];
  clientDescription: string;
}) {
  const date = new Date();
  return (
    <div className="mx-auto max-w-[800px] p-5 text-[14px] leading-relaxed text-slate-800">
      <div className="text-center border-b-2 border-blue-600 pb-4 mb-5">
        <h1 className="text-[24px] font-bold text-blue-600 m-0">
          Goodwill Central Texas
        </h1>
        <p className="m-0">GenAI Referral Tool - Client Referral Report</p>
        <p className="m-0" suppressHydrationWarning>
          Generated on {date.toLocaleDateString()} at{" "}
          {date.toLocaleTimeString()}
        </p>
      </div>
      <ClientDetailsPromptBubble clientDescription={clientDescription} />
      <ResourcesList resources={resources ?? []} handleRemoveResource={() => {}} />

      <div className="text-center text-slate-500 text-[12px] mt-5 pt-4 border-t border-slate-200">
        Report generated by Goodwill Central Texas GenAI Referral Tool
      </div>
    </div>
  );
}
