import { Resource } from "@/types/resources";
import React from "react";
import ResourcesList from "@/components/ResourcesList";
import ClientDetailsPromptBubble from "@/components/ClientDetailsPromptBubble";
import { ActionPlanDisplay } from "@/components/ActionPlanDisplay";
import { ActionPlan } from "@/util/fetchActionPlan";
import { CompactResourceList } from "@/components/CompactResourceList";
import { PrintMode } from "@/components/PrintOptionsDialog";

export function PrintableReferralsReport({
  resources,
  clientDescription,
  actionPlan,
  selectedCategories = [],
  locationText = "",
  selectedResourceTypes = [],
  printMode = "full-referrals",
  selectedResources = [],
}: {
  resources: Resource[];
  clientDescription: string;
  actionPlan?: ActionPlan | null;
  selectedCategories?: string[];
  locationText?: string;
  selectedResourceTypes?: string[];
  printMode?: PrintMode;
  selectedResources?: Resource[];
}) {
  const date = new Date();
  const isActionPlanOnly = printMode === "action-plan-only";

  return (
    <div className="mx-auto max-w-[800px] p-5 text-[14px] leading-relaxed text-slate-800">
      <div className="border-b border-slate-300 pb-3 mb-4">
        <h1 className="text-[24px] font-bold text-slate-900 m-0">
          Your Resource Guide from Goodwill
        </h1>
        <div className="flex items-center justify-between mt-1">
          <p className="text-[13px] text-slate-600 m-0">
            {isActionPlanOnly
              ? "Personalized action plan and resources"
              : "Personalized resources selected for you"}
          </p>
          <p className="text-[12px] text-slate-500 m-0" suppressHydrationWarning>
            {date.toLocaleDateString()}
          </p>
        </div>
      </div>
      <ClientDetailsPromptBubble
        clientDescription={clientDescription}
        selectedCategories={selectedCategories}
        locationText={locationText}
        selectedResourceTypes={selectedResourceTypes}
      />

      {isActionPlanOnly ? (
        <>
          {/* Compact resource list at top (contact info only, no descriptions) */}
          <CompactResourceList resources={selectedResources} />
          {/* Action Plan after resources */}
          {actionPlan && (
            <div className="print:mt-3">
              <ActionPlanDisplay actionPlan={actionPlan} />
            </div>
          )}
        </>
      ) : (
        <>
          {/* Full referrals with descriptions */}
          <ResourcesList
            resources={resources ?? []}
            handleRemoveResource={() => {}}
          />
          {actionPlan && (
            <div className="print:mt-3">
              <ActionPlanDisplay actionPlan={actionPlan} />
            </div>
          )}
        </>
      )}

      <div className="text-center text-slate-500 text-[12px] mt-5 pt-4 border-t border-slate-200">
        Report generated by Goodwill Central Texas GenAI Referral Tool
      </div>
    </div>
  );
}
