# Changes here will be overwritten by Copier
_commit: v0.15.7
_src_path: https://github.com/navapbc/template-infra
base_code_repository_url: https://github.com/NavaPBC/labs-referral-pilot
base_default_region: us-east-1
base_owner: NavaPBC
base_project_name: labs-referral-pilot
template: base
