services:
  app-db:
    image: postgres:16-alpine
    command: postgres -c "log_lock_waits=on" -N 1000 -c "fsync=off"
    environment:
      POSTGRES_PASSWORD: secret123
      # Set user to app to match user from template-infra (https://github.com/navapbc/template-infra)
      # This is also needed for the initial migration that alters defaut privileges to grant
      # table privileges to the app user (see src/db/migrations/versions/2023_08_10_default_table_privileges.py)
      POSTGRES_USER: app
    ports:
      - "5432:5432"
    volumes:
      - app-dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app"]
      interval: 10s
      timeout: 5s
      retries: 5

  phoenix:
    image: arizephoenix/phoenix:version-10.9.1-nonroot
    depends_on:
      - app-db
    ports:
      - "6006:6006" # UI and OTLP HTTP collector
      # - "4317:4317" # OTLP gRPC collector
    environment:
      # https://arize.com/docs/phoenix/self-hosting/features/authentication
      # - PHOENIX_ENABLE_AUTH=True
      # - PHOENIX_SECRET=${PHOENIX_SECRET}
      - PHOENIX_SQL_DATABASE_URL=postgresql://app:secret123@app-db:5432/postgres


  # Since Phoenix doesn't have a status or healthcheck endpoint,
  # sleep for a while before starting the backend service,
  # which queries Phoenix for prompt templates during startup.
  wait_for_phoenix:
    image: alpine:latest
    entrypoint: /bin/sh -c "for i in $(seq 1 30); do nc -z phoenix 6006 && exit 0; sleep 1; done; echo 'Phoenix did not become ready in time.'; exit 1"

  app:
    build:
      context: ./
      target: dev
      args:
        - RUN_UID=${RUN_UID:-4000}
        - RUN_USER=${RUN_USER:-app}
    ports:
      # For Hayhooks
      - "3000:3000"
    volumes:
      - ./:/app
    env_file:
      - path: ./local.env
        required: true
      - path: ./override.env
        required: false
    depends_on:
      app-db:
        condition: service_healthy
      wait_for_phoenix:
        condition: service_completed_successfully

volumes:
  app-dbdata:
