services:
  app-db:
    image: postgres:16-alpine
    command: postgres -c "log_lock_waits=on" -N 1000 -c "fsync=off"
    environment:
      POSTGRES_PASSWORD: secret123
      # Set user to app to match user from template-infra (https://github.com/navapbc/template-infra)
      # This is also needed for the initial migration that alters defaut privileges to grant
      # table privileges to the app user (see src/db/migrations/versions/2023_08_10_default_table_privileges.py)
      POSTGRES_USER: app
    ports:
      - "5432:5432"
    volumes:
      - app-dbdata:/var/lib/postgresql/data

  app:
    build:
      context: ./
      target: dev
      args:
        - RUN_UID=${RUN_UID:-4000}
        - RUN_USER=${RUN_USER:-app}
    ports:
      # For Hayhooks
      - "1416:1416"
    environment:
      # Set API keys for LLM clients from .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

    env_file:
      - path: ./local.env
        required: true


volumes:
  app-dbdata:
