"""create support table

Revision ID: 9f6564648027
Revises: 62c305ccb067
Create Date: 2025-09-03 15:48:53.914985

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9f6564648027"
down_revision = "62c305ccb067"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "support",
        sa.Column("support_listing_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False, comment="Human usable name for the support"),
        sa.Column(
            "addresses",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            comment="The address(es), as a list, of the the support resource(s)",
        ),
        sa.Column(
            "phone_numbers",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            comment="The phone number(s), as a list, of the the support resource(s)",
        ),
        sa.Column(
            "description", sa.Text(), nullable=True, comment="Description summarizing the resource"
        ),
        sa.Column(
            "website", sa.Text(), nullable=True, comment="The full URL for the specific resource"
        ),
        sa.Column(
            "email_addresses",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            comment="The email address(es) as a list to contact the referral resource",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["support_listing_id"],
            ["support_listing.id"],
            name=op.f("support_support_listing_id_support_listing_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("support_pkey")),
        sa.UniqueConstraint("name", name=op.f("support_name_uniq")),
    )
    op.alter_column(
        "support_listing",
        "name",
        existing_type=sa.TEXT(),
        comment="name of the support listing; a human-use identifier",
        existing_nullable=False,
    )
    op.alter_column(
        "support_listing",
        "uri",
        existing_type=sa.TEXT(),
        comment="origin of the Support Listing; a file path or a website URL",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "support_listing",
        "uri",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="origin of the Support Listing; a file path or a website URL",
        existing_nullable=False,
    )
    op.alter_column(
        "support_listing",
        "name",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="name of the support listing; a human-use identifier",
        existing_nullable=False,
    )
    op.drop_table("support")
    # ### end Alembic commands ###
