"""Make CrawlJob prompt_name optional

Revision ID: 5909cc18ab46
Revises: f5741ad3f14d
Create Date: 2025-11-03 17:32:15.482498

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5909cc18ab46"
down_revision = "f5741ad3f14d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "crawl_job",
        "prompt_name",
        existing_type=sa.TEXT(),
        nullable=True,
        comment="Name of the prompt to use for this crawl job (optional if using scraper function)",
        existing_comment="Name of the prompt to use for this crawl job",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "crawl_job",
        "prompt_name",
        existing_type=sa.TEXT(),
        nullable=False,
        comment="Name of the prompt to use for this crawl job",
        existing_comment="Name of the prompt to use for this crawl job (optional if using scraper function)",
    )
    # ### end Alembic commands ###
