"""add table for LLM response

Revision ID: 6efaf354b5c3
Revises: e7fc051e7823
Create Date: 2025-10-17 20:42:31.652794

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6efaf354b5c3"
down_revision = "e7fc051e7823"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_response",
        sa.Column(
            "raw_text",
            sa.Text(),
            nullable=False,
            comment="The raw string of the LLM response; may contain JSON string",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("llm_response_pkey")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("llm_response")
    # ### end Alembic commands ###
