"""create support listing table

Revision ID: 4d134292e5e3
Revises: 4ff1160282d1
Create Date: 2025-09-03 15:56:17.655320

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4d134292e5e3"
down_revision = "4ff1160282d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "support_listing",
        sa.Column(
            "name",
            sa.Text(),
            nullable=False,
            comment="name of the support listing; a human-readable identifier",
        ),
        sa.Column(
            "uri",
            sa.Text(),
            nullable=False,
            comment="origin of the Support Listing; a file path or a website URL",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("support_listing_pkey")),
        sa.UniqueConstraint("name", name=op.f("support_listing_name_uniq")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("support_listing")
    # ### end Alembic commands ###
