"""Add last_crawled_at

Revision ID: f5741ad3f14d
Revises: 5b265c0b0dec
Create Date: 2025-10-23 13:25:05.561013

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f5741ad3f14d"
down_revision = "5b265c0b0dec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "crawl_job",
        sa.Column(
            "last_crawled_at",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Timestamp of the last successful crawl",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("crawl_job", "last_crawled_at")
    # ### end Alembic commands ###
