"""create support table

Revision ID: dfb8d1c41707
Revises: 4d134292e5e3
Create Date: 2025-09-03 20:06:17.387035

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "dfb8d1c41707"
down_revision = "4d134292e5e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "support",
        sa.Column("support_listing_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False, comment="Human usable name for the support"),
        sa.Column(
            "addresses",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            comment="The address(es), as a list, of the the support resource(s)",
        ),
        sa.Column(
            "phone_numbers",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            comment="The phone number(s), as a list, of the the support resource(s)",
        ),
        sa.Column(
            "description", sa.Text(), nullable=True, comment="Description summarizing the resource"
        ),
        sa.Column(
            "website", sa.Text(), nullable=True, comment="The full URL for the specific resource"
        ),
        sa.Column(
            "email_addresses",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            comment="The email address(es) as a list to contact the referral resource",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["support_listing_id"],
            ["support_listing.id"],
            name=op.f("support_support_listing_id_support_listing_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("support_pkey")),
        sa.UniqueConstraint("name", name=op.f("support_name_uniq")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("support")
    # ### end Alembic commands ###
