"""Add crawl job

Revision ID: 5b265c0b0dec
Revises: 6efaf354b5c3
Create Date: 2025-10-22 15:08:16.491872

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5b265c0b0dec"
down_revision = "6efaf354b5c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_job",
        sa.Column(
            "prompt_name",
            sa.Text(),
            nullable=False,
            comment="Name of the prompt to use for this crawl job",
        ),
        sa.Column("domain", sa.Text(), nullable=False, comment="Domain to crawl"),
        sa.Column(
            "crawling_interval",
            sa.Integer(),
            nullable=False,
            comment="Crawling interval in hours (positive integer)",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("crawl_job_pkey")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("crawl_job")
    # ### end Alembic commands ###
