"""create support listing table

Revision ID: 62c305ccb067
Revises: 4ff1160282d1
Create Date: 2025-08-29 21:46:56.658243

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "62c305ccb067"
down_revision = "4ff1160282d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "support_listing",
        sa.Column("id", sa.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("name", sa.Text()),
        sa.Column("uri", sa.Text()),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("support_listing")
    # ### end Alembic commands ###
