"""Remove deprecated/unused tables

Revision ID: 484711f5be4a
Revises: 5909cc18ab46
Create Date: 2026-01-26 18:34:43.371347

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "484711f5be4a"
down_revision = "5909cc18ab46"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("support")
    op.drop_table("support_listing")
    op.drop_table("crawl_job")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_job",
        sa.Column(
            "prompt_name",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Name of the prompt to use for this crawl job (optional if using scraper function)",
        ),
        sa.Column(
            "domain", sa.TEXT(), autoincrement=False, nullable=False, comment="Domain to crawl"
        ),
        sa.Column(
            "crawling_interval",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Crawling interval in hours (positive integer)",
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_crawled_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
            comment="Timestamp of the last successful crawl",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("crawl_job_pkey")),
        sa.UniqueConstraint(
            "domain",
            name=op.f("crawl_job_domain_uniq"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "support_listing",
        sa.Column(
            "name",
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            comment="name of the support listing; a human-readable identifier",
        ),
        sa.Column(
            "uri",
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            comment="origin of the Support Listing; a file path or a website URL",
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="support_listing_pkey"),
        sa.UniqueConstraint(
            "name",
            name="support_listing_name_uniq",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "support",
        sa.Column("support_listing_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "name",
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            comment="The name for the support resource",
        ),
        sa.Column(
            "addresses",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=False,
            comment="The address(es), as a list, of the support resource",
        ),
        sa.Column(
            "phone_numbers",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=False,
            comment="The phone number(s), as a list, of the support resource",
        ),
        sa.Column(
            "description",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Description summarizing the resource",
        ),
        sa.Column(
            "website",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="The full URL for the resource",
        ),
        sa.Column(
            "email_addresses",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=False,
            comment="The email address(es) as a list to contact the resource",
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["support_listing_id"],
            ["support_listing.id"],
            name=op.f("support_support_listing_id_support_listing_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("support_pkey")),
    )
    # ### end Alembic commands ###
