name: 'Run experiment'

on:
  workflow_dispatch:
    inputs:
      dataset_name:
        description: 'Name of the Phoenix dataset to use'
        type: string
        required: true
      pipeline_name:
        description: 'Name of the pipeline to run'
        type: choice
        options:
          - 'generate-referrals'
        default: 'generate-referrals'
        required: true

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run experiment
      shell: bash
      env:
        DEPLOYED_PHOENIX_URL: ${{ secrets.DEPLOYED_PHOENIX_URL }}
        DEPLOYED_PHOENIX_API_KEY: ${{ secrets.DEPLOYED_PHOENIX_API_KEY }}
        DEPLOYED_API_URL: ${{ secrets.DEPLOYED_API_URL }}
      run: |
        make run-experiment DATASET="${{ github.event.inputs.dataset_name }}" ACTION="run_on_deployed"
